variables:
  TAG: ""
stages:
  - set_tag
  - run

set-tag:
  stage: set_tag
  script:
    - cd test-execution
    - npm install
    - npm run build
    - npm run start-init-execution-keywords $suiteId
    - $TAG = Get-Content .\execution_keywords.txt -Raw

run-tests:
  tags:
    - $TAG
  stage: run
  script:
    - cd test-execution
    - npm install
    - npm run build
    - echo $testsToRun
    - $testsToRunModified = '"' + $testsToRun.Replace("`n","").Replace('"',"'") + '"'
    - echo "$testsToRunModified"
    - npm run start-uft "$testsToRunModified" $suiteId $suiteRunId $username $password
    - powershell ./UFTExecutorGitlab.ps1
  artifacts:
    paths:
      - .\test-execution\build\*
      - .\test-execution\testResults\*