def agentLabel = ""
pipeline{
    agent any
    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }
    parameters {
        string(name: 'testsToRun',description: '' )
        string(name: 'nunit2',defaultValue: 'C:\\NUnitExecution\\NUnit-2.7.1\\bin\\nunit-console.exe',description: '' )
        string(name: 'nunit3',defaultValue: 'C:\\NUnitExecution\\Nunit3\\nunit3-console.exe' )
        string(name: 'suiteId',description: '' )
        string(name: 'suiteRunId',description: '' )
    }

    stages {

        stage('setTag') {

            steps {
                dir('test-execution') {
                    bat 'npm install'
                    bat 'npm run build'
                    bat 'echo getting execution keywords from the test suite'
                    bat 'npm run start-init-execution-keywords %suiteId%"'
                    script {
                          agentLabel = readFile('execution_keywords.txt').trim()
                    }
                }

            }
        }

        stage('Run Tests') {
            agent{
                label agentLabel
            }
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: '6cfdfdfd-819b-49cb-9b55-64b7c444326b', usernameVariable: 'username', passwordVariable: 'password')]) {
                        dir('test-execution') {
                            bat 'npm install'
                            bat 'npm run build'
                            bat 'call npm run start-nunit "%testsToRun%" %suiteId% %suiteRunId% %nunit2% %nunit3% %username% %password%'
                            bat 'call echo "running tests..."'
                            try {
                                bat 'call command_to_execute.bat'
                            } catch(err) {
                                bat 'echo Tests failed! Continue...'
                            }
                            bat 'call java_command_to_execute.bat'
                        }

                    }
                }
                archiveArtifacts artifacts: 'test-execution/java_command_to_execute.bat,test-execution/command_to_execute.bat,test-execution/testResults/**', onlyIfSuccessful: false
                junit allowEmptyResults: true, testResults: 'test-execution/testResults/*/*.xml'

            }

        }

    }
    post {
        always {
            node(agentLabel) {
               cleanWs()
            }
            cleanWs()
        }
    }

}
